// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC9iJnHh0HJAaI1YfBEZAAFxVNWThUtwQ',
    appId: '1:644655850118:android:f60d94623dad931fdae707',
    messagingSenderId: '644655850118',
    projectId: 'flash-chat-4c1d9',
    storageBucket: 'flash-chat-4c1d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQjLsrMrEJZFq0I_OGJURly4_mAxt25Ik',
    appId: '1:644655850118:ios:e622265a8486886fdae707',
    messagingSenderId: '644655850118',
    projectId: 'flash-chat-4c1d9',
    storageBucket: 'flash-chat-4c1d9.appspot.com',
    iosClientId: '644655850118-5fm92v6590dfn1ug7gm5hkg7u0kdrg6e.apps.googleusercontent.com',
    iosBundleId: 'com.lovesaemi.flashchat',
  );
}
